// @mattiwheels
 
s0.initVideo("https://media.giphy.com/media/PCOOG9p4shWUg/giphy.mp4")

// effects
noise(5,1)
  .modulateScale(osc(1,0,0),1)
  .pixelate(3,3)
  //.kaleid()
  .contrast(1.5)
  .out(o0)
osc(1,1,1)
  .kaleid(2)
  .blend(osc(3,0,5).rotate(15,0), .5)
  .rotate(20,0)
  .out(o1)
voronoi(8,1,0)
  .blend(o0, -1)
  .rotate(0,.2)
  .brightness(-0.5)
  .kaleid(2)
  .out(o2)
// output 03
src(s0)
  .blend(o1, 2)
  .contrast(1)
  .rotate(0,.1)
  .modulate(o2)
  .invert()
  .brightness(.2)
  .saturate(.5)
  .scale(.5)
  .kaleid(2)
  .out(o3)
render(o3)
